# SWMAL Exercise

## Mathematical Foundation

### Vector and matrix representation in python

In this exercise be about vector and matrix representation in Python. Firstly there will be showed how to implement a array in python. The secondly will the $\norm{1}$ and $\norm{2}$ be implemented without using `sqrt` or other mathmatical operator from math the library. 

#### Qa Given the following $\mathbf{x}^{(i)}$'s, construct and print the $\mathbf X$ matrix in python.

$$
    \ar{rl}{
      \bx\pown{1} &= \ac{c}{ 1, 2, 3}^T \\
      \bx\pown{2} &= \ac{c}{ 4, 2, 1}^T \\
      \bx\pown{3} &= \ac{c}{ 3, 8, 5}^T \\
      \bx\pown{4} &= \ac{c}{-9,-1, 0}^T
    }
$$

##### Implementation Details


For using the Python in the course you will have to get familiar with Python and the librabries.

In this chapter we will show how you can implement a array using numpy. You can either create the hole array at ones or you can use the append function. The append take two array a put the toghter in a new array. Another function is the vstack, where the function vertical stack each element. 

In [2]:
import numpy as np
y = np.array([1, 2, 3, 4]) # NOTE:  you'll need this later

# Default method
X = np.array([[1, 2, 3],[4, 2, 1], [3, 8, 5], [-9, -1, 0]])

# print the full matrix
print(f"{X}")

# use the vstack
np.vstack(([1, 2, 3],[4, 2, 1], [3, 8, 5], [-9, -1, 0]))



# Use append 
q= np.array([[1, 2, 3],[4, 2, 1]] ) # NOTE:  you'll need this later
q = np.append(q, [[4, 2, 1], [3, 8, 5], [-9, -1, 0]],axis = 0)

# print the full matrix
#print(f"{q}")

[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


### Norms, metrics or distances

#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.

Here we will ilustrate how to use the norms, metrices or distances. The first thing you will notice below is two function for error validation, that belongs to a exercise that will be decribes later on. The test of the validation is done up here, we will explain alot more later on. Just below the validation function, you can observe the L1, L2 and L2Dot. The L1 is given the distance between two vectors. Therefore, it takes the absolute value and sum all numbers together.

$$
    \ar{ll}{      
          \mbox{d}(\bx,\by) &= ||\bx-\by||_2\\
                     &= \left( \sum_{i=1}^n \left| x_{i}-y_{i} \right|^2 \right)^{1/2}
    }
$$ 

 The $$ L2 is the Eucalidian distance or norm for a vector. You can define it though a sum operation or a dot operation. Dot opeeration is vector multiply it self

$$
    \norm{2}:~~ ||\bx||_2 = \left( \sum_{i=1}^{n} |x_i|^2 \right)^{1/2}\\
$$


In [12]:
import math

def checkArraySizeCoantainsElements(X):
    assert X.shape[0]>=0 
    if not X.ndim==1:
        raise Exception("Array size needs to bigger than 1 dimision")

def checkArraySize(X):
    assert X.shape[0]>=0 and X.shape[1]==0
    if not X.ndim==1:
        raise Exception("Array size needs to bigger than 1 dimision")

def L1(X):
    checkArraySizeCoantainsElements(X)
    return sum((Xi**2)**0.5 for Xi in X) 


def L2(X):
    checkArraySizeCoantainsElements(X)
    return sum((Xi*Xi) for Xi in X) **(1/2)

def L2Dot(X):
    return np.sqrt(np.dot(X,X))


# Test the function with the following vectors
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)
d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 
# NOTE: remember to import 'math' for fabs for the next two lines..
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

print("OK(part-1)")

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert math.fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 
print("OK(part-2)")

tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
OK(part-1)
d2dot-expected_d2= 0.0
OK(part-2)


## The cost function, $J$

Now, most ML algorithm uses norms or metrics internally when doing minimizations. Details on this will come later, but for now we need to know that an algorithm typically tries to minimize a given performance metric, the loss function, for all the input data, and implicitly tries to minimize the sum of all norms for the 'distances' between some predicted output, $y\st{pred}$ and the true output $y\st{true}$, with the distance between these typically given by the $\norm{2}$ norm

$$   
  \mbox{individual loss:}~~L\powni = \mbox{d}(y\st{pred}\powni,y\st{true}\powni)
$$ 

with $y\st{pred}\powni$, a scalar value, being the output from the hypothesis function, that maps the input vector $\bx\powni$ to a scalar

$$ 
    y_{pred}\powni = \hat{y}\powni = h(\bx\powni;\btheta)
$$

and the total loss, $J$ will be the sum over all $i$'s

$$
    \ar{rl}{
        J &= \frac{1}{n} \sum_{i=1}^{n} L\powni\\
        &= \frac{1}{n} \sum_{i=1}^{n} \mbox{d}( h(\bx\powni) , y\powni\st{true})
    }
$$


### Cost function in vector/matrix notation using $\norm{2}$

Remember the data-flow model for supervised learning

<img src="https://itundervisning.ase.au.dk/SWMAL/L02/Figs/ml_simple_vector.png" alt="WARNING: could not get image from server." style="width:500px">

Let us now express $J$ in terms of vectors and matrices instead of summing over individual scalars, and let's use $\norm{2}$ as the distance function

$$
    \ar{rl}{
        J(\bX,\by;\btheta) &= \frac{1}{n} \sum_{i=1}^{n} L\powni\\
        &= \frac{1}{n}\sum_{i=1}^{n} (h(\bx\powni) - \by\powni\st{true})^2\\
        &= \frac{1}{n} ||h(\bX) - \by\st{true} ||_2^2\\
        &= \frac{1}{n} ||\by\st{pred} - \by\st{true} ||_2^2\\
     }
$$

with the matrix-vector notation

$$ 
    \by_{pred} = \hat{\by} =  h(\bX;\btheta)
$$

#### Loss or Objective Function using the Mean Squared Error

This formulation is equal to the definition of the _mean-squared-error_, MSE (or indirectly also RMSE), here given in the general formulation for some random variable $Z$ 

$$
    \ar{rl}{
        \mbox{MSE} &= \frac{1}{n} \sum_{i=1}^{n} (\hat{Z}_i-Z_i)^2 = \frac{1}{n} SS\\
        \mbox{RMSE} &= \sqrt{\mbox{MSE}}\
    }
$$

with sum-of-squares (SS) is given simply by

$$
    \mbox{SS} = \sum_{i=1}^{n} (\hat{Z}_i-Z_i)^2\\
$$


So, using the $\norm{2}$ for the distance metric, is equal to saying that we want to minimize $J$ with respect to the MSE

$$
    \ar{rl}{
        J &= \mbox{MSE}(h(\bX), \by\st{true}) \\
          &= \mbox{MSE}(\by\st{pred}~, \by\st{true}) \\
          &= \mbox{MSE}(\hat{\by}, \by\st{true})
     }
$$

Note: when minimizing one can ignore the constant factor $1/n$ and it really does not matter if you minimize MSE or RMSE. Often $J$ is also multiplied by 1/2 to ease notation when trying to differentiate it.

$$
    \ar{rl}{
        J(\bX,\by\st{true};\btheta) &\propto \half ||\by\st{pred} - \by\st{true} ||_2^2 \\
          &\propto \mbox{MSE}
     }
$$

### MSE

Now, let us take a look on how you calculate the MSE.

The MSE uses the $\norm{2}$ norm internally, well, actually $||\cdot||^2_2$ to be precise, and basically just sums, means and roots the individual (scalar) losses (distances), we just saw before. 

And the RMSE is just an MSE with a final square-root call.

### Qc Construct the Root Mean Square Error (RMSE) function (Equation 2-1 [HOML]).

Call the function RMSE, and evaluate it using the $\bX$ matrix and $\by$ from Qa.

We implement a dummy hypothesis function, that just takes the first column of $\bX$ as its 'prediction'

$$
    h\st{dummy}(\bX) = \bX(:,0)
$$

Do not re-implement the $\norm{2}$ for the RMSE function, but call the '''L2''' function you just implemented internally in RMSE.

In [4]:
# TODO: solve Qc...implement your RMSE function here
# IDK Have it call the L2, but you har to take h(x)-y
def RMSE(X,y):
    checkArraySizeContains(y)
        
    dif_array = X - y
    print(dif_array)
    return (L2(dif_array))/2 # Why divide with 2?? we should divide with m and there is only two numbers in the dif array

#print(np.dot(h(X),y))

        
# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Delete me - Jusst for seeing the values
print(y)
print(f"hX: {h(X)}")

# Calls your RMSE() function:
r=RMSE(h(X),y)
MSE = np.square(np.subtract(h(X),y)).mean() 
 
RMSE = math.sqrt(MSE)
print("Root Mean Square Error:\n")
print(RMSE)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

print("OK")

[1 2 3 4]
hX: [ 1  4  3 -9]


NameError: name 'checkArraySizeContains' is not defined

### MAE

#### Qd Similar construct the Mean Absolute Error (MAE) function (Equation 2-2 [HOML]) and evaluate it.

The MAE will algorithmic wise be similar to the MSE part from using the $\norm{1}$ instead of the $\norm{2}$ norm.

Again, re-implementation of the$\norm{1}$ is a no-go, call the '''L1''' instead internally i MAE.

In [ ]:
def MAE(X,y):
    
    return L1(X-y)/X.size

# Calls your MAE function:
r=MAE(h(X), y)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
#assert math.fabs(r-expected)<eps, "MAE dist seems to be wrong" 

print("OK")

MAE=3.75, diff=0.0
OK


## Pythonic Code

### Robustness of Code

Data validity checking is an essential part of robust code, and in Python the 'fail-fast' method is used extensively: instead of lingering on trying to get the 'best' out of an erroneous situation, the fail-fast pragma will be very loud about any data inconsistencies at the earliest possible moment.

Hence robust code should include a lot of error checking, say as pre- and post-conditions (part of the design-by-contract programming) when calling a function: when entering the function you check that all parameters are ok (pre-condition), and when leaving you check the return parameter (post-conditions).  

Normally assert-checking or exception-throwing will do the trick just fine, with the exception method being more _pythonic_.

For the norm-function you could, for instance, test your input data to be 'vector' like, i.e. like

```python
    assert x.shape[0]>=0 and x.shape[1]==0
    
    if not x.ndim==1:
        raise some error
```
or similar.

#### Qe Robust Code 

Add error checking code (asserts or exceptions), that checks for right $\hat\by$-$\by$ sizes of the MSE and MAE functions.

Also add error checking to all you previously tested L2() and L1() functions, and re-run all your tests.

### Qf Conclusion

Now, conclude on all the exercise above. 

Write a short textual conclusion (max. 10- to 20-lines) that extract the _essence_ of the exercises: why did you think it was important to look at these particular ML concepts, and what was our overall learning outcome of the exercises (in broad terms).

In [ ]:
# TODO: Qf concluding remarks in text.. 