# SWMAL Exercise

## Mathematical Foundation

### Vector and matrix representation in python


$$
    \newcommand\rem[1]{}
    \rem{SWMAL: CEF def and LaTeX commands, remember: no newlines in defs}
    \newcommand\eq[2]{#1 &=& #2\\}
    \newcommand\ar[2]{\begin{array}{#1}#2\end{array}}
    \newcommand\ac[2]{\left[\ar{#1}{#2}\right]}
    \newcommand\st[1]{_{\scriptsize #1}}
    \newcommand\norm[1]{{\cal L}_{#1}}
    \newcommand\obs[2]{#1_{\text{\scriptsize obs}}^{\left(#2\right)}}
    \newcommand\diff[1]{\text{d}#1}
    \newcommand\pown[1]{^{(#1)}}
    \def\pownn{\pown{n}}
    \def\powni{\pown{i}}
    \def\powtest{\pown{\text{\scriptsize test}}}
    \def\powtrain{\pown{\text{\scriptsize train}}}
    \def\bX{\mathbf{M}}
    \def\bX{\mathbf{X}}
    \def\bZ{\mathbf{Z}}
    \def\bw{\mathbf{m}}
    \def\bx{\mathbf{x}}
    \def\by{\mathbf{y}}
    \def\bz{\mathbf{z}}
    \def\bw{\mathbf{w}}
    \def\btheta{{\boldsymbol\theta}}
    \def\bSigma{{\boldsymbol\Sigma}}
    \def\half{\frac{1}{2}}
$$

This exercise is about vector and matrix representation in Python. Firstly, there will be showed how to implement an array in python. Secondly, the $\norm{1}$ and $\norm{2}$ will be implemented without using `sqrt` or other mathmatical operators from math the library. 

#### Qa Given the following $\mathbf{x}^{(i)}$'s, construct and print the $\mathbf X$ matrix in python.

$$
    \ar{rl}{
      \bx\pown{1} &= \ac{c}{ 1, 2, 3}^T \\
      \bx\pown{2} &= \ac{c}{ 4, 2, 1}^T \\
      \bx\pown{3} &= \ac{c}{ 3, 8, 5}^T \\
      \bx\pown{4} &= \ac{c}{-9,-1, 0}^T
    }
$$


For using the Python in the course we will have to get familiar with Python and the libraries.

In this chapter we will show how you can implement an array using numpy. You can either create the whole array at once or you can use the append function. The append take two arrays and put them together in a new array. Another function is the vstack, where the function vertically stack each element. 

In [2]:
import numpy as np
y = np.array([1, 2, 3, 4]) # NOTE:  you'll need this later

# Default method
X = np.array([[1, 2, 3],[4, 2, 1], [3, 8, 5], [-9, -1, 0]])

# print the full matrix
print(f"X = \n{X}")

# use the vstack
np.vstack(([1, 2, 3],[4, 2, 1], [3, 8, 5], [-9, -1, 0]))



# Use append 
q= np.array([[1, 2, 3],[4, 2, 1]] ) # NOTE:  you'll need this later
q = np.append(q, [[3, 8, 5], [-9, -1, 0]],axis = 0)

# print the full matrix
print(f"q = \n{q}")

X = 
[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]
q = 
[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


### Norms, metrics or distances

#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.

Here we will ilustrate how to use the norms, metrices or distances. The first thing you will notice below is two functions for error validation, that belongs to an exercise that will be decribed later on. The test of the validation is done up here, we will explain alot more later on. Just below the validation function, you can observe the L1, L2 and L2Dot. The L1 is given the distance between two vectors. Therefore, it takes the absolute value and sum all numbers together.


$$
    \ar{ll}{      
          \text{d}(\bx,\by) &= ||\bx-\by||_2\\
                     &= \left( \sum_{i=1}^n \left| x_{i}-y_{i} \right|^2 \right)^{1/2}
    }
$$ 

 The L2 is the Eucalidian distance or norm for a vector. You can define it through a sum operation or a dot operation. Dot operation is vector multiplied with itself

$$
    \norm{2}:~~ ||\bx||_2 = \left( \sum_{i=1}^{n} |x_i|^2 \right)^{1/2}\\
$$ 



In [2]:
import math

def checkArraySize(X):
    assert X.shape[0]>=0
    if not X.ndim==1:
        raise Exception("Array size needs to bigger than 1 dimision")

def L1(X):
    checkArraySize(X)
    return sum((Xi**2)**0.5 for Xi in X) 


def L2(X):
    checkArraySize(X)
    return sum((Xi*Xi) for Xi in X) **(1/2)

def L2Dot(X):
    return np.sqrt(np.dot(X,X))


# Test the function with the following vectors
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)
d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 
# NOTE: remember to import 'math' for fabs for the next two lines..
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

print("OK(part-1)")

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert math.fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 
print("OK(part-2)")

tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
OK(part-1)
d2dot-expected_d2= 0.0
OK(part-2)


## The cost function, $J$
### Qc Construct the Root Mean Square Error (RMSE) function (Equation 2-1 [HOML]).

We will here show how to call the function Root Mean Square Error (RMSE), by using the $\bX$ matrix and $\by$ from Qa. 
There will be implemented a dummy hypothesis function. With this function we will be taking the first column of $\bX$ as its 'prediction'

$$
    h\st{dummy}(\bX) = \bX(:,0)
$$

We will be calling the '''L2''' function that has been implemented internally in RMSE


In [3]:
def RMSE(X,y):
    dif_array = X - y
    checkArraySize(dif_array)  
    return (L2(dif_array))*0.5
        
# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Calls your RMSE() function:
r=RMSE(h(X),y)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

print("OK")

RMSE=6.576473218982953, diff=2.6645352591003757e-15
OK


### MAE

#### Qd Similar construct the Mean Absolute Error (MAE) function (Equation 2-2 [HOML]) and evaluate it.

As we just created a function for the RMSE, we also want to create a function for the Mean Absolute Error (MAE). The MAE will internally use the $\norm{1}$

$$
    \ar{rl}{
        \text{MSE} &= \frac{1}{n} \sum_{i=1}^{n} (\hat{Z}_i-Z_i)^2 = \frac{1}{n} SS\\
        \text{RMSE} &= \sqrt{\text{MSE}}\
    }
$$
  

In [4]:
def MAE(X,y):
    checkArraySize(X)
    L1(X-y)
    return L1(X-y)/X.size

# Calls your MAE function:
r=MAE(h(X), y)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "MAE dist seems to be wrong" 

print("OK")

MAE=3.75, diff=0.0
OK


## Pythonic Code

#### Qe Robust Code 

We have added error checking code (asserts or exceptions), that checks for right $\hat\by$-$\by$ sizes of the MSE and MAE functions.

We have also error checking to all the previously tested L2() and L1() functions. as can be seen in the following code block 

In [2]:
def checkArraySize(X):
    assert X.shape[0]>=0
    if not X.ndim==1:
        raise Exception("Array size needs to bigger than 1 dimision")

def L1(X):
    checkArraySize(X)
    return sum((Xi**2)**0.5 for Xi in X) 


def L2(X):
    checkArraySize(X)
    return sum((Xi*Xi) for Xi in X) **(1/2)

def RMSE(X,y):
    dif_array = X - y
    checkArraySize(dif_array)  
    return (L2(dif_array))*0.5

def MAE(X,y):
    checkArraySize(X)
    L1(X-y)
    return L1(X-y)/X.size

### Qf Conclusion


In this exercise we have implemented the L1 and L2 distance functions. We have also manually implemented the RMSE and MAE functions without the use of built-in function. We have tested the functions with the given vectors and the results are as expected. This is to learn and become familiar with the formulars and functions. And get a better understanding the math behind the methods often used in Machine Learning. Lastly, we also have learned how to check if the functionality is correct in the functions by adding error checking in our python code.